-- ============================================================================
-- MindBridge — Supabase schema
-- Run this ONCE in the Supabase SQL Editor (safe to re-run: everything is
-- "if not exists" / "or replace", so your existing `patients` table survives).
--
-- Workflow it supports:
--   caretaker creates an account (caretaker name, patient name, email,
--   password, language) -> signs in -> patient dashboard (games) and
--   caretaker dashboard (daily + overall progress) read the same rows.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. PATIENTS  (one row per account: the patient + their caretaker)
-- ---------------------------------------------------------------------------
create table if not exists public.patients (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  name text not null,
  age integer default 72,
  region text default 'Imphal, Manipur',
  preferred_language text default 'English',
  streak integer default 0,
  created_at timestamptz not null default now()
);

-- Repair older patients tables that were created without the primary key.
alter table public.patients add column if not exists id uuid default gen_random_uuid();
update public.patients set id = gen_random_uuid() where id is null;
alter table public.patients alter column id set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.patients'::regclass
      and contype = 'p'
  ) then
    alter table public.patients add constraint patients_pkey primary key (id);
  end if;
end $$;

-- New columns for the caretaker-led signup flow (no-ops if already present).
alter table public.patients add column if not exists caretaker_name    text;
alter table public.patients add column if not exists caretaker_mobile  text;
alter table public.patients add column if not exists caretaker_email   text;
alter table public.patients add column if not exists language_code     text default 'en';
alter table public.patients add column if not exists updated_at        timestamptz not null default now();

update public.patients as p
set caretaker_email = u.email
from auth.users as u
where p.user_id = u.id
  and nullif(u.email, '') is not null
  and p.caretaker_email is null;

drop index if exists public.patients_caretaker_mobile_key;

create index if not exists patients_user_id_idx on public.patients (user_id);

-- ---------------------------------------------------------------------------
-- 2. GAME SCORES  (every completed cognitive session)
-- ---------------------------------------------------------------------------
create table if not exists public.game_scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  game_type text not null,
  score integer not null check (score between 0 and 100),
  attempts integer not null default 1,
  created_at timestamptz not null default now()
);

alter table public.game_scores add column if not exists category         text;
alter table public.game_scores add column if not exists duration_seconds integer default 180;
alter table public.game_scores add column if not exists difficulty       text default 'easy';

create index if not exists game_scores_user_created_idx
  on public.game_scores (user_id, created_at desc);

create index if not exists game_scores_user_local_day_idx
  on public.game_scores (user_id, ((created_at at time zone 'Asia/Kolkata')::date));

-- ---------------------------------------------------------------------------
-- 3. COGNITIVE ALERTS  (caregiver reminders + acknowledgements)
-- ---------------------------------------------------------------------------
create table if not exists public.cognitive_alerts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  alert_title text not null,
  status text not null default 'Acknowledged',
  created_at timestamptz not null default now()
);

alter table public.cognitive_alerts add column if not exists alert_body text;
alter table public.cognitive_alerts add column if not exists kind       text default 'reminder';
alter table public.cognitive_alerts add column if not exists caretaker_email text;

update public.cognitive_alerts as a
set caretaker_email = p.caretaker_email
from public.patients as p
where a.user_id = p.user_id
  and a.caretaker_email is null
  and p.caretaker_email is not null;

create index if not exists cognitive_alerts_user_created_idx
  on public.cognitive_alerts (user_id, created_at desc);

-- ---------------------------------------------------------------------------
-- 4. CARE GIFTS  (audio recordings and photos from the caretaker)
-- ---------------------------------------------------------------------------
create table if not exists public.care_gifts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  gift_type text not null check (gift_type in ('audio', 'photo')),
  title text not null,
  file_name text not null,
  mime_type text not null,
  media_data text not null,
  unlock_score integer not null default 90 check (unlock_score between 0 and 100),
  created_at timestamptz not null default now()
);

create index if not exists care_gifts_user_created_idx
  on public.care_gifts (user_id, created_at desc);

-- ---------------------------------------------------------------------------
-- 4. ROW LEVEL SECURITY
--    The server authenticates every request with the Supabase access token
--    before it touches these tables; RLS is the second boundary inside the DB.
-- ---------------------------------------------------------------------------
alter table public.patients         enable row level security;
alter table public.game_scores      enable row level security;
alter table public.cognitive_alerts enable row level security;
alter table public.care_gifts       enable row level security;

drop policy if exists "own patient row select" on public.patients;
create policy "own patient row select" on public.patients
  for select using (auth.uid() = user_id);

drop policy if exists "own patient row insert" on public.patients;
create policy "own patient row insert" on public.patients
  for insert with check (auth.uid() = user_id);

drop policy if exists "own patient row update" on public.patients;
create policy "own patient row update" on public.patients
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "own patient row delete" on public.patients;
create policy "own patient row delete" on public.patients
  for delete using (auth.uid() = user_id);

drop policy if exists "own scores select" on public.game_scores;
create policy "own scores select" on public.game_scores
  for select using (auth.uid() = user_id);

drop policy if exists "own scores insert" on public.game_scores;
create policy "own scores insert" on public.game_scores
  for insert with check (auth.uid() = user_id);

drop policy if exists "own alerts select" on public.cognitive_alerts;
create policy "own alerts select" on public.cognitive_alerts
  for select using (auth.uid() = user_id);

drop policy if exists "own alerts insert" on public.cognitive_alerts;
create policy "own alerts insert" on public.cognitive_alerts
  for insert with check (auth.uid() = user_id);

drop policy if exists "own alerts update" on public.cognitive_alerts;
create policy "own alerts update" on public.cognitive_alerts
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "own gifts select" on public.care_gifts;
create policy "own gifts select" on public.care_gifts
  for select using (auth.uid() = user_id);

drop policy if exists "own gifts insert" on public.care_gifts;
create policy "own gifts insert" on public.care_gifts
  for insert with check (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- 5. SIGNUP TRIGGER
--    Creates the patients row the instant an account is created, using the
--    metadata the server sends with signUp(). Runs as security definer so it
--    works even when the server only holds the anon key.
-- ---------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.patients (
    user_id, name, caretaker_name, caretaker_mobile, caretaker_email,
    preferred_language, language_code, age, region
  )
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data ->> 'patient_name', ''), 'Patient'),
    coalesce(nullif(new.raw_user_meta_data ->> 'caretaker_name', ''), 'Caretaker'),
    nullif(new.raw_user_meta_data ->> 'mobile', ''),
    nullif(new.email, ''),
    coalesce(nullif(new.raw_user_meta_data ->> 'preferred_language', ''), 'English'),
    coalesce(nullif(new.raw_user_meta_data ->> 'language_code', ''), 'en'),
    coalesce((new.raw_user_meta_data ->> 'age')::int, 72),
    coalesce(nullif(new.raw_user_meta_data ->> 'region', ''), 'Imphal, Manipur')
  )
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- ---------------------------------------------------------------------------
-- 6. DAILY PROGRESS VIEW  (what the caretaker dashboard summarises)
--    security_invoker keeps RLS in force: a caretaker only ever sees their own
--    patient's days.
-- ---------------------------------------------------------------------------
create or replace view public.daily_progress
with (security_invoker = true) as
select
  gs.user_id,
  (gs.created_at at time zone 'Asia/Kolkata')::date as day,
  count(*)                                       as sessions,
  round(avg(gs.score))::int                     as avg_score,
  max(gs.score)                                  as best_score,
  min(gs.score)                                  as low_score,
  round(sum(coalesce(gs.duration_seconds, 180)) / 60.0)::int as minutes,
  p.streak                                      as streak
from public.game_scores as gs
join public.patients as p on p.user_id = gs.user_id
group by gs.user_id, (gs.created_at at time zone 'Asia/Kolkata')::date, p.streak;

-- Keep the cached patient streak current whenever a session is recorded.
create or replace function public.calculate_and_update_streak()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  local_today date := (now() at time zone 'Asia/Kolkata')::date;
  latest_day date;
  calculated_streak integer := 0;
begin
  with date_list as (
    select distinct (created_at at time zone 'Asia/Kolkata')::date as game_date
    from public.game_scores
    where user_id = new.user_id
  )
  select max(game_date)
  into latest_day
  from date_list;

  if latest_day >= local_today - 1 then
    with date_list as (
      select distinct (created_at at time zone 'Asia/Kolkata')::date as game_date
      from public.game_scores
      where user_id = new.user_id
    ),
    ranked_days as (
      select game_date,
             row_number() over (order by game_date desc) - 1 as days_back
      from date_list
    )
    select count(*)::integer
    into calculated_streak
    from ranked_days
    where game_date = latest_day - days_back::integer;
  end if;

  update public.patients
  set streak = calculated_streak,
      updated_at = now()
  where user_id = new.user_id;

  return new;
end;
$$;

drop trigger if exists update_streak_on_score_insert on public.game_scores;
create trigger update_streak_on_score_insert
after insert on public.game_scores
for each row execute procedure public.calculate_and_update_streak();

-- Word Garden history is not required by the application.
drop table if exists public.word_garden_history;
