-- Run this once in Supabase SQL Editor.
create table if not exists public.patients (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  name text not null,
  age integer default 72,
  region text default 'Imphal, Manipur',
  preferred_language text default 'English',
  streak integer default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.game_scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  game_type text not null,
  score integer not null check (score between 0 and 100),
  attempts integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.cognitive_alerts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  alert_title text not null,
  status text not null default 'Acknowledged',
  created_at timestamptz not null default now()
);

alter table public.patients enable row level security;
alter table public.game_scores enable row level security;
alter table public.cognitive_alerts enable row level security;

create policy "Patients can read their own profile" on public.patients
  for select using (auth.uid() = user_id);
create policy "Patients can read their own scores" on public.game_scores
  for select using (auth.uid() = user_id);
create policy "Patients can create their own scores" on public.game_scores
  for insert with check (auth.uid() = user_id);
create policy "Patients can create their own alerts" on public.cognitive_alerts
  for insert with check (auth.uid() = user_id);

-- Optional: create a profile automatically whenever a user signs up.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.patients (user_id, name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1)))
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();
