-- ============================================================================
-- MindBridge — Supabase schema
-- Run this ONCE in the Supabase SQL Editor (safe to re-run: everything is
-- "if not exists" / "or replace", so your existing `patients` table survives).
--
-- Workflow it supports:
--   caretaker creates an account (caretaker name, patient name, email,
--   password, language) -> signs in -> patient dashboard (games) and
--   caretaker dashboard (daily + overall progress) read the same rows.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. PATIENTS  (one row per account: the patient + their caretaker)
-- ---------------------------------------------------------------------------
create table if not exists public.patients (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  name text not null,
  age integer default 72,
  region text default 'Imphal, Manipur',
  preferred_language text default 'English',
  streak integer default 0,
  created_at timestamptz not null default now()
);

-- New columns for the caretaker-led signup flow (no-ops if already present).
alter table public.patients add column if not exists caretaker_name    text;
alter table public.patients add column if not exists caretaker_mobile  text;
alter table public.patients add column if not exists language_code     text default 'en';
alter table public.patients add column if not exists updated_at        timestamptz not null default now();

drop index if exists public.patients_caretaker_mobile_key;

create index if not exists patients_user_id_idx on public.patients (user_id);

-- ---------------------------------------------------------------------------
-- 2. GAME SCORES  (every completed cognitive session)
-- ---------------------------------------------------------------------------
create table if not exists public.game_scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  game_type text not null,
  score integer not null check (score between 0 and 100),
  attempts integer not null default 1,
  created_at timestamptz not null default now()
);

alter table public.game_scores add column if not exists category         text;
alter table public.game_scores add column if not exists duration_seconds integer default 180;
alter table public.game_scores add column if not exists difficulty       text default 'easy';

create index if not exists game_scores_user_created_idx
  on public.game_scores (user_id, created_at desc);

-- ---------------------------------------------------------------------------
-- 3. COGNITIVE ALERTS  (caregiver reminders + acknowledgements)
-- ---------------------------------------------------------------------------
create table if not exists public.cognitive_alerts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  alert_title text not null,
  status text not null default 'Acknowledged',
  created_at timestamptz not null default now()
);

alter table public.cognitive_alerts add column if not exists alert_body text;
alter table public.cognitive_alerts add column if not exists kind       text default 'reminder';

create index if not exists cognitive_alerts_user_created_idx
  on public.cognitive_alerts (user_id, created_at desc);

-- ---------------------------------------------------------------------------
-- 4. CARE GIFTS  (audio recordings and photos from the caretaker)
-- ---------------------------------------------------------------------------
create table if not exists public.care_gifts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  gift_type text not null check (gift_type in ('audio', 'photo')),
  title text not null,
  file_name text not null,
  mime_type text not null,
  media_data text not null,
  unlock_score integer not null default 90 check (unlock_score between 0 and 100),
  created_at timestamptz not null default now()
);

create index if not exists care_gifts_user_created_idx
  on public.care_gifts (user_id, created_at desc);

-- ---------------------------------------------------------------------------
-- 4. ROW LEVEL SECURITY
--    The server authenticates every request with the Supabase access token
--    before it touches these tables; RLS is the second boundary inside the DB.
-- ---------------------------------------------------------------------------
alter table public.patients         enable row level security;
alter table public.game_scores      enable row level security;
alter table public.cognitive_alerts enable row level security;
alter table public.care_gifts       enable row level security;

drop policy if exists "own patient row select" on public.patients;
create policy "own patient row select" on public.patients
  for select using (auth.uid() = user_id);

drop policy if exists "own patient row insert" on public.patients;
create policy "own patient row insert" on public.patients
  for insert with check (auth.uid() = user_id);

drop policy if exists "own patient row update" on public.patients;
create policy "own patient row update" on public.patients
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "own scores select" on public.game_scores;
create policy "own scores select" on public.game_scores
  for select using (auth.uid() = user_id);

drop policy if exists "own scores insert" on public.game_scores;
create policy "own scores insert" on public.game_scores
  for insert with check (auth.uid() = user_id);

drop policy if exists "own alerts select" on public.cognitive_alerts;
create policy "own alerts select" on public.cognitive_alerts
  for select using (auth.uid() = user_id);

drop policy if exists "own alerts insert" on public.cognitive_alerts;
create policy "own alerts insert" on public.cognitive_alerts
  for insert with check (auth.uid() = user_id);

drop policy if exists "own alerts update" on public.cognitive_alerts;
create policy "own alerts update" on public.cognitive_alerts
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "own gifts select" on public.care_gifts;
create policy "own gifts select" on public.care_gifts
  for select using (auth.uid() = user_id);

drop policy if exists "own gifts insert" on public.care_gifts;
create policy "own gifts insert" on public.care_gifts
  for insert with check (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- 5. SIGNUP TRIGGER
--    Creates the patients row the instant an account is created, using the
--    metadata the server sends with signUp(). Runs as security definer so it
--    works even when the server only holds the anon key.
-- ---------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.patients (
    user_id, name, caretaker_name, caretaker_mobile,
    preferred_language, language_code, age, region
  )
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data ->> 'patient_name', ''), 'Patient'),
    coalesce(nullif(new.raw_user_meta_data ->> 'caretaker_name', ''), 'Caretaker'),
    nullif(new.raw_user_meta_data ->> 'mobile', ''),
    coalesce(nullif(new.raw_user_meta_data ->> 'preferred_language', ''), 'English'),
    coalesce(nullif(new.raw_user_meta_data ->> 'language_code', ''), 'en'),
    coalesce((new.raw_user_meta_data ->> 'age')::int, 72),
    coalesce(nullif(new.raw_user_meta_data ->> 'region', ''), 'Imphal, Manipur')
  )
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- ---------------------------------------------------------------------------
-- 6. DAILY PROGRESS VIEW  (what the caretaker dashboard summarises)
--    security_invoker keeps RLS in force: a caretaker only ever sees their own
--    patient's days.
-- ---------------------------------------------------------------------------
create or replace view public.daily_progress
with (security_invoker = true) as
select
  user_id,
  (created_at at time zone 'Asia/Kolkata')::date as day,
  count(*)                                       as sessions,
  round(avg(score))::int                         as avg_score,
  max(score)                                     as best_score,
  min(score)                                     as low_score,
  round(sum(coalesce(duration_seconds, 180)) / 60.0)::int as minutes
from public.game_scores
group by user_id, (created_at at time zone 'Asia/Kolkata')::date;

-- ============================================================================
-- WORD GARDEN HISTORY  (track used words to prevent repetition)
-- ============================================================================

create table if not exists public.word_garden_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  word text not null,
  prompt text not null,
  created_at timestamptz not null default now()
);

create index if not exists word_garden_history_user_idx
  on public.word_garden_history (user_id, created_at desc);

alter table public.word_garden_history enable row level security;

drop policy if exists "own words" on public.word_garden_history;
create policy "own words" on public.word_garden_history
  for all using (auth.uid() = user_id);
